db.js, routes/legacy/api.js, routes/matches/matches.js
A few changes are being made and breaking backwards compatibility. Moving away from Steamworks and sm-json and moving towards Rest in PAWN. Please download the latest plugin available [here](https://github.com/PhlexPlexico/get5-webapi/releases)
=> Plugin rewrite

db.js, package.json, yarn.lock
Possible attempt to fix the broken database calls after a certain amount of database links are created.
Technically `query` is supposed to open and close a connection, but it's likely that this may not be the case, since we try to close a null connection. So the plan is to take that up a level and hope this may fix it.
=> Attempting database fix at source class.

__test__/vetosides.test.js, jest_config/jest.vetosides.config.js, migrations/development/20210107194928-get5db.js, migrations/production/20210107194928-get5db.js, migrations/test/20210107194928-get5db.js, package.json, routes/legacy/api.js, routes/vetosides.js
Add in API call for side types.
=> Add side types table for vetoes.

utility/utils.js
=> accept ID and API token only as HTTP Headers

.travis.yml, package.json
=> Migrate to Node.js version 14

routes/servers.js
=> Fix Bug not allowing authentication at `/servers`

app.js, jest_config/jest.vetosides.config.js, migrations/development/20210124162658-get5db.js, migrations/development/20210201015955-get5db.js, migrations/production/20210124162658-get5db.js, migrations/production/20210201015955-get5db.js, migrations/test/20210124162658-get5db.js, migrations/test/20210201015955-get5db.js, package.json, routes/leaderboard.js, routes/legacy/api.js, routes/playerstats.js, routes/teams.js, yarn.lock
Re-doing as feature branch was messed from rebase.
Closes #73.
> This change incorporates new stats that may be a part of get5. Including a re-implemented check of flashbang assists. enemies flashed, friendlies flashed, and utility damage.
=> Add 4 New Stats To Track

Caddyfile, README.md, docker-compose.yml
Setup should be easier than ever for full stack!
=> Docker compose implemented.

.github/workflows/ghcr.yml
Reforked the whole repo, to have it as 1 commit. Does the same as PhlexPlexico/G5V#89 but for the API.
=> Added GHCR CD

routes/users.js, utility/auth.js, utility/utils.js
=> Consolidate API key with user ID.

migrations/development/20210124162658-get5db.js, migrations/development/20210201015955-get5db.js, migrations/development/20211125150429-get5db.js, migrations/production/20210124162658-get5db.js, migrations/production/20210201015955-get5db.js, migrations/production/20211125150429-get5db.js, migrations/test/20210124162658-get5db.js, migrations/test/20210201015955-get5db.js, migrations/test/20211125150429-get5db.js, routes/legacy/api.js, routes/matches/matchserver.js
This should resolve #108 and help organization for team names after a PUG.
=> De-normalize team names.

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ghcr.yml, Dockerfile
This merge now allows us to build on raspberry pi's and host on more portable devices.
=> Add arm arch to builds

routes/teams.js
Starting work for SVG uploads. This takes a look at base64 encoded data and converts it to an SVG on the server. There is still a lot of work needing to be done on this to ensure safety of the system as well.
=> SVG Uploads (#187)

routes/legacy/api.js, routes/matches/matches.js, routes/matches/matchserver.js
Fix POST errors on demo uploads. This now checks the param for API keys as well.
Matches are shown in GET immediately when created.
Match restart route has been implemented.
Match GET endpoints now have a query param of `asc=true` to allow for matches in ascending order of IDs.
Closes #205
=> Event Feedback Fixes

Dockerfile
a.k.a. fix my hours of trouble after update
=> add back the port exposure

README.md, config/development.json.template, config/test.json.template, migrations/development/20220713153034-get5db.js, migrations/production/20220713153034-get5db.js, migrations/test/20220713153034-get5db.js, routes/matches/matches.js, routes/matches/matchserver.js, routes/teams.js, utility/serverrcon.js
Match configs will now provide coaches and not have them in the player array.
Update configs for the redis URL with an example for passwords.
=> Include adding coaches to the system.

routes/legacy/api.js, routes/matches/matchserver.js, yarn.lock
Update pauseType in unpause to null.
Update to delete player stats on match restart.
=> Lock update.

routes/matches/matchserver.js
They can be retrieved via GET.
=> Add in full text instead of round num + map num.

routes/playerstats.js
- Add new endpoint `/playerstats/:steam_id/season/:season_id` to fetch player stat in a specific season.
- Extract duplicated code to function `getPlayerStats`.
=> Add new endpoint /playerstats/:steam_id/season/:season_id

migrations/20220907171148-get5db.js, migrations/development/20191109191155-get5db.js, migrations/development/20220907171148-get5db.js, migrations/production/20191109191155-get5db.js, migrations/production/20220907171148-get5db.js, migrations/test/20191109191155-get5db.js, migrations/test/20220907171148-get5db.js, routes/matches/matches.js
This should close #225.
We are now able to allow users to select sides and do vetoes outside of the game itself, while letting them select what sides belong where, or if they need to knife,
=> Bring in map_sides to post, put, and config get calls.

Dockerfile, README.md, package.json
Express Update
Closes #267 - The named database in the compose file and when building and running an image will be properly respected.
=> Version 2.0.2.3

src/routes/legacy/api.ts, src/routes/matches/matchserver.ts, src/utility/serverrcon.ts
Remove some hanging references to G5WS.
Update error message for `isGet5Available`.
=> Change final scores on forfeit to be MR13.
